# your informations
author:
  name: Sam Van Den Berge
  description: Software Engineer
  picture: /assets/images/avatar_opt.jpg

# Site settings
title: Sam Van Den Berge
url: http://samvandenberge.be
paginate: 5

# site version
version: 1.0.0

# your github username
github_username: samvandenberge

# set true to include or false to exclude share option
share:
  twitter: false
  facebook: false
  google_plus: false
  linkedin: true
  disqus: false

# Build settings
markdown: kramdown
highlighter: pygments
exclude: [ 'README.md', 'src/', 'node_modules', 'bower_components', 'package.json', 'bower.json', 'Gruntfile.js' ]

# Plugins
gems:
  - jekyll-sitemap
