# your informations
author:
  name: Sam Van Den Berge
  description: Software Engineer
  picture: /assets/images/avatar_opt.jpg

# Site settings
title: Sam Van Den Berge
url: https://samvandenberge.be
paginate: 4

# site version
version: 1.0.0

# your github username
github_username: samvandenberge

# set true to include or false to exclude share option
share:
  twitter: false
  facebook: false
  google_plus: true
  linkedin: true
  disqus: false

# Build settings
markdown: kramdown
highlighter: rouge
exclude: [ 'README.md', 'src/', 'node_modules', 'bower_components', 'package.json', 'bower.json', 'Gruntfile.js', 'tools']

# Plugins
gems: [jekyll-paginate, rouge]